
SET SERVEROUTPUT ON;

DECLARE
    cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO cnt 
    FROM ALL_DIRECTORIES 
    WHERE DIRECTORY_NAME = 'VENTES_DIR';
    
    IF cnt > 0 THEN
        EXECUTE IMMEDIATE 'DROP DIRECTORY VENTES_DIR';
    END IF;
    
    EXECUTE IMMEDIATE 'CREATE DIRECTORY VENTES_DIR AS ''/home/oracle/Documents''';
    EXECUTE IMMEDIATE 'GRANT READ ON DIRECTORY VENTES_DIR TO PUBLIC';
    
    DBMS_OUTPUT.PUT_LINE('Dossier VENTES_DIR ok');
END;
/

DECLARE
    cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO cnt FROM USER_TABLES WHERE TABLE_NAME = 'VENTES_EXT';
    IF cnt > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE VENTES_EXT';
    END IF;
END;
/

CREATE TABLE VENTES_EXT (
    IdVente NUMBER,
    IdClient NUMBER,
    NomClient VARCHAR2(100),
    PrenomClient VARCHAR2(100),
    EmailClient VARCHAR2(200),
    IdMagasin NUMBER,
    NomMagasin VARCHAR2(100),
    CodePostalMagasin NUMBER,
    ListeAchats VARCHAR2(4000),
    DateAchat VARCHAR2(10),
    URLTicket VARCHAR2(500)
)
ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY VENTES_DIR
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        CHARACTERSET UTF8
        FIELDS TERMINATED BY ';'
        MISSING FIELD VALUES ARE NULL
    )
    LOCATION ('ventes_games.txt')
)
REJECT LIMIT UNLIMITED;

DECLARE
    nb_lignes NUMBER;
BEGIN
    SELECT COUNT(*) INTO nb_lignes FROM VENTES_EXT;
    DBMS_OUTPUT.PUT_LINE('Table externe creee: ' || nb_lignes || ' lignes');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erreur lecture fichier - verifier /home/oracle/Documents');
END;
/
