SET SERVEROUTPUT ON;

BEGIN
    FOR t IN (SELECT table_name FROM user_tables 
              WHERE table_name LIKE 'DB2_%') LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('Tables DB2 nettoyees');
END;
/

CREATE TABLE DB2_CLIENTS (
    IdClient NUMBER PRIMARY KEY,
    NomClient VARCHAR2(100),
    PrenomClient VARCHAR2(100),
    EmailClient VARCHAR2(200) UNIQUE
);

CREATE TABLE DB2_ARTICLES (
    IdArticle NUMBER,
    LibelleArticle VARCHAR2(200),
    Console VARCHAR2(50),
    PRIMARY KEY (IdArticle, Console)
);

CREATE TABLE DB2_MAGASINS (
    IdMagasin NUMBER PRIMARY KEY,
    NomMagasin VARCHAR2(100),
    CodePostalMagasin NUMBER,
    CONSTRAINT CK_DB2_MAGASINS_CP CHECK (CodePostalMagasin >= 5000 AND CodePostalMagasin <= 9999)
);

CREATE TABLE DB2_VENTES (
    IdVente NUMBER PRIMARY KEY,
    IdClient NUMBER REFERENCES DB2_CLIENTS(IdClient),
    IdMagasin NUMBER REFERENCES DB2_MAGASINS(IdMagasin),
    DateAchat DATE,
    URLTicket VARCHAR2(500),
    TICKET_BLOB BLOB
);

CREATE TABLE DB2_LIGNES_VENTES (
    IdLigneVente NUMBER PRIMARY KEY,
    IdVente NUMBER REFERENCES DB2_VENTES(IdVente) ON DELETE CASCADE,
    IdArticle NUMBER,
    Console VARCHAR2(50),
    Prix NUMBER(10,2),
    Quantite NUMBER,
    FOREIGN KEY (IdArticle, Console) REFERENCES DB2_ARTICLES(IdArticle, Console)
);

INSERT INTO DB2_CLIENTS SELECT * FROM PROJETBD1.CLIENTS;

INSERT INTO DB2_ARTICLES SELECT * FROM PROJETBD1.ARTICLES;

INSERT INTO DB2_MAGASINS 
SELECT * FROM PROJETBD1.MAGASINS 
WHERE CodePostalMagasin >= 5000 AND CodePostalMagasin <= 9999;

INSERT INTO DB2_VENTES (IdVente, IdClient, IdMagasin, DateAchat, URLTicket, TICKET_BLOB)
SELECT vnt.IdVente, vnt.IdClient, vnt.IdMagasin, vnt.DateAchat, vnt.URLTicket, vnt.TICKET_BLOB
FROM PROJETBD1.VENTES vnt
JOIN PROJETBD1.MAGASINS mag ON vnt.IdMagasin = mag.IdMagasin
WHERE mag.CodePostalMagasin >= 5000 AND mag.CodePostalMagasin <= 9999;

INSERT INTO DB2_LIGNES_VENTES
SELECT lgn.*
FROM PROJETBD1.LIGNES_VENTES lgn
JOIN PROJETBD1.VENTES vnt ON lgn.IdVente = vnt.IdVente
JOIN PROJETBD1.MAGASINS mag ON vnt.IdMagasin = mag.IdMagasin
WHERE mag.CodePostalMagasin >= 5000 AND mag.CodePostalMagasin <= 9999;

COMMIT;

SELECT 'DB2 - Clients :' AS Info, COUNT(*) AS Nb FROM DB2_CLIENTS
UNION ALL
SELECT 'DB2 - Articles :', COUNT(*) FROM DB2_ARTICLES
UNION ALL
SELECT 'DB2 - Magasins (5000-9999) :', COUNT(*) FROM DB2_MAGASINS
UNION ALL
SELECT 'DB2 - Ventes :', COUNT(*) FROM DB2_VENTES
UNION ALL
SELECT 'DB2 - Details ventes :', COUNT(*) FROM DB2_LIGNES_VENTES;
